exclude: |
  (?x)(
    ^target/|
    ^src/github/gql[.]ts$|
    ^src/github/schema[.]graphql$
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
        priority: 0
      - id: check-case-conflict
        priority: 0
      - id: check-executables-have-shebangs
        priority: 0
      - id: check-json
        priority: 0
      - id: check-merge-conflict
        priority: 0
      - id: check-shebang-scripts-are-executable
        priority: 0
      - id: check-symlinks
        priority: 0
      - id: check-toml
        priority: 0
      - id: check-vcs-permalinks
        priority: 0
      - id: check-xml
        priority: 0
      - id: check-yaml
        priority: 0
      - id: detect-private-key
        priority: 0
      - id: mixed-line-ending
        args: ["--fix=no"]
        priority: 0
      - id: no-commit-to-branch
        priority: 0
  - repo: https://github.com/crate-ci/typos
    rev: v1.42.3
    hooks:
      - id: typos
        args: []
        priority: 0
  - repo: local
    hooks:
      - id: deno-check
        name: deno check
        description: Check all TypeScript source code files.
        entry: deno check
        exclude: ^backend/
        pass_filenames: false
        language: system
        priority: 0
      - id: deno run vitest:run
        name: vitest
        description: Run vitest
        entry: deno run vitest:run
        exclude: ^backend/
        pass_filenames: false
        language: system
        priority: 0
      - id: api-types-check
        name: api types check
        description: Ensure API types are up-to-date
        entry: sh -c 'deno run generate:api --silent && git diff --exit-code src/api/ || (echo "Error - API types are out of date. Run deno run generate:api" && exit 1)'
        language: system
        exclude: ^backend/
        pass_filenames: false
        priority: 100
  - repo: https://github.com/nozaq/pre-commit-deno
    rev: 0.1.0
    hooks:
      - id: deno-fmt-check
        priority: 0
      - id: deno-lint
        priority: 0
      - id: deno-test
        priority: 0
