repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=no"]
        exclude: "^rust-crate/target/"
      - id: no-commit-to-branch
  - repo: https://github.com/crate-ci/typos
    rev: v1.40.0
    hooks:
      - id: typos
        args: []
        exclude: "^rust-crate/target/"
  - repo: local
    hooks:
      - id: cargo clippy
        name: cargo clippy
        language: system
        entry: cargo clippy --manifest-path rust-crate/Cargo.toml --all-targets --all-features -- -D warnings
        args: []
        files: (\.rs|Cargo\.toml)$
        pass_filenames: false
      - id: cargo doc
        name: cargo doc
        language: system
        entry: sh -c 'RUSTDOCFLAGS=-Dwarnings cargo doc --manifest-path rust-crate/Cargo.toml --all-features --workspace --no-deps --document-private-items' --
        args: []
        files: \.rs$
        pass_filenames: false
      - id: cargo fmt
        name: cargo fmt
        language: system
        entry: cargo fmt --manifest-path rust-crate/Cargo.toml --check
        args: []
        files: (\.rs|rustfmt\.toml)$
        pass_filenames: false
      - id: deno-check
        name: deno check
        description: Check all TypeScript source code files.
        entry: deno check
        types_or: [ts, tsx]
        pass_filenames: false
        language: system
  - repo: https://github.com/nozaq/pre-commit-deno
    rev: 0.1.0
    hooks:
      - id: deno-fmt-check
      - id: deno-lint
      - id: deno-test
        args: ["--permit-no-files"]
