name: TS checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: deno check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          cache: true
      - run: deno install --frozen
      - run: deno check

  fmt:
    name: deno fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          cache: true
      - run: deno fmt --check

  lint:
    name: deno lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          cache: true
      - run: deno lint

  test:
    name: deno test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          cache: true
      - run: deno install --frozen
      - run: deno test

  vitest:
    name: vitest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          cache: true
      - run: deno install --frozen
      - run: deno run vitest:run
